version: '2'

services:


    nginx:
        image: nginx:alpine
        ports:
            - "14290:5080"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            
        links:
            - cert_detect_api
            - frontend

    frontend:
        
        build: ./frontend

        ports:
            - "14291:5080"

        volumes:
            - ./frontend/build:/build
        
