version: '2'

services:


    nginx:
        image: nginx:alpine
        ports:
            - "14288:5080"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            
        links:
            - cert_detect_api
            - frontend

    cert_detect_api:
        
        build: ./backend/api
        
        volumes:
            - ./backend/db:/db
        ports:
            - "14289:5080"
        links:
            - cert_detect_worker

    cert_detect_worker:
        
        build: ./backend/worker
        
        volumes:
            - ./backend/db:/db

    frontend:
        
        build: ./frontend

        ports:
            - "14287:5080"

        volumes:
            - ./frontend/build:/build
        
